/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ODIN_PB_H_INCLUDED
#define PB_ODIN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _odin_proto_parameter {
    int32_t id;
    pb_callback_t data;
} odin_proto_parameter;

typedef struct _odin_proto_parameter_collection {
    pb_callback_t parameters;
} odin_proto_parameter_collection;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define odin_proto_parameter_init_default        {0, {{NULL}, NULL}}
#define odin_proto_parameter_collection_init_default {{{NULL}, NULL}}
#define odin_proto_parameter_init_zero           {0, {{NULL}, NULL}}
#define odin_proto_parameter_collection_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define odin_proto_parameter_id_tag              1
#define odin_proto_parameter_data_tag            2
#define odin_proto_parameter_collection_parameters_tag 3

/* Struct field encoding specification for nanopb */
#define odin_proto_parameter_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    id,                1) \
X(a, CALLBACK, REQUIRED, BYTES,    data,              2)
#define odin_proto_parameter_CALLBACK pb_default_field_callback
#define odin_proto_parameter_DEFAULT NULL

#define odin_proto_parameter_collection_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  parameters,        3)
#define odin_proto_parameter_collection_CALLBACK pb_default_field_callback
#define odin_proto_parameter_collection_DEFAULT NULL
#define odin_proto_parameter_collection_parameters_MSGTYPE odin_proto_parameter

extern const pb_msgdesc_t odin_proto_parameter_msg;
extern const pb_msgdesc_t odin_proto_parameter_collection_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define odin_proto_parameter_fields &odin_proto_parameter_msg
#define odin_proto_parameter_collection_fields &odin_proto_parameter_collection_msg

/* Maximum encoded size of messages (where known) */
/* odin_proto_parameter_size depends on runtime parameters */
/* odin_proto_parameter_collection_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
